### ISSUE TITLE
scan_interval_seconds dont work?

### ISSUE THREAD

**Issue by CLAM01** [fuslwusl/homeassistant-edl21-custom-interval#5]
Hi, i tried to use the edl21 integration.
i have create a folder named "edl21" over the HA UI (File Editor) into "custom_components" an copy the 3 files into this folder.
Then i have configured the configuration.yaml as follow:

```
######################################
############### EDL21 ################
sensor:
  - platform: edl21
    name: "Heizstrom"
    serial_port: socket://192.168.1.133:1234
    scan_interval_seconds: 15
```

but after restart home assistant, the updates comes in every 60 oder 90 seconds.
Please help me to find my mistake.

**Comment by fuslwusl** [comment]
Follow these steps and it should work:
1. **Uninstall the official edl21 integration**
2. **Restart Homeassistant**
3. Add this custom integration
4. Add the configuration for example:
    ```
    sensor:
      - platform: edl21
        serial_port: /dev/serial/by-id/usb-FTDI_FT230X_Basic_UART_D306NKQQ-if00-port0
        scan_interval_seconds: 5
    ```
5. Restart Homeassistant
6. Check if it works or logs for errors
